### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Senexis** [timotejroiko/discord.js-light#6]
Hi, just here to report an issue I've just noticed within Discord JS light. Somehow, it seems possible that a new guild member can come through with an undefined ID, crashing the app. Please let me know whether this is an issue you can resolve or which I should take up to Discord JS.

Sadly, as this is an automated logging which happened about 16 minutes ago at the time of writing, I don't know much more than this as it was not in a development situation but in a live bot. It's worth noting that this bot has been fine for multiple weeks now, and this is the first issue I seemingly am not able to resolve myself.

Thank you for the library and I hope I'm both at the right place and that I can get this issue resolved with you.

Cheers!

```
Aug 06 09:20:34.447am info app TypeError: Cannot read property 'id' of undefined
Aug 06 09:20:34.447am info app at GuildMemberManager.Discord.GuildMemberManager.add (/app/node_modules/discord.js-light/classes.js:460:103)
Aug 06 09:20:34.447am info app at Message._patch (/app/node_modules/discord.js-light/classes.js:31:28)
Aug 06 09:20:34.447am info app at new Message (/app/node_modules/discord.js-light/node_modules/discord.js/src/structures/Message.js:43:20)
Aug 06 09:20:34.447am info app at new Message (/app/node_modules/discord.js-light/classes.js:6:9)
Aug 06 09:20:34.447am info app at Immediate.<anonymous> (/app/node_modules/discord.js-light/actions.js:29:29)
Aug 06 09:20:34.447am info app at processImmediate (internal/timers.js:458:21)
Aug 06 09:20:34.447am info app at MessageManager.add (/app/node_modules/discord.js-light/node_modules/discord.js/src/managers/BaseManager.js:49:32)
Aug 06 09:20:34.447am info app at MessageManager.add (/app/node_modules/discord.js-light/node_modules/discord.js/src/managers/MessageManager.js:29:18)
Aug 06 09:20:34.447am info app at MessageCreateAction.client.actions.MessageCreate.handle (/app/node_modules/discord.js-light/actions.js:221:34)
Aug 06 09:20:34.447am info app at Object.PacketHandlers.MESSAGE_CREATE (/app/node_modules/discord.js-light/handlers.js:170:49)
```

**Comment by timotejroiko** [comment]
Hey there, i believe this issue was fixed in one of the recent updates, which version are you currently using? Can you try updating to 3.1.1?

**Comment by Senexis** [comment]
Will do. I'll let you know if I run into this again. Closing for now.
