### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by LosTigeros** [timotejroiko/discord.js-light#80]
Hey, I'm getting this error:
```typescript
TypeError: Cannot read properties of null (reading 'members')
    at Message._patch (./node_modules/discord.js-light/extensions.js:80:78)
    at Message._update (./node_modules/discord.js/src/structures/Base.js:30:10)
    at MessageUpdateAction.MessageUpdate [as handle] (./node_modules/discord.js-light/actions.js:402:18)
    at Object.MESSAGE_UPDATE (./node_modules/discord.js-light/handlers.js:268:57)
    at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
    at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (./node_modules/ws/lib/websocket.js:1022:20)
```

`GuildManager` cache is on `Infinity`.

**Comment by timotejroiko** [comment]
should be fixed in 4.2.1

**Comment by LosTigeros** [comment]
Can confirm, the issue is fixed, thanks!
