### ISSUE TITLE
Error in makePartial and in actions

### ISSUE THREAD

**Issue by LosTigeros** [timotejroiko/discord.js-light#88]
Hello.

Most of the shards on my bot crashed early today due to this error:
```
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at makePartial (./node_modules/discord.js-light/functions.js:26:9)
    at ChannelUpdateAction.ChannelUpdate [as handle] (./node_modules/discord.js-light/actions.js:64:4)
    at Object.CHANNEL_UPDATE (./node_modules/discord.js-light/handlers.js:99:57)
    at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
    at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (./node_modules/ws/lib/websocket.js:1098:20)
```

I also got a notification about this one a few days ago:
```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at ThreadListSyncAction.ThreadListSync [as handle] (./node_modules/discord.js-light/actions.js:667:33)
    at Object.THREAD_LIST_SYNC (./node_modules/discord.js-light/handlers.js:376:33)
    at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
    at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (./node_modules/ws/lib/websocket.js:1098:20)
    at Receiver.emit (node:events:390:28)
```

Also do you have a Discord server where I could ask if I set up the caching properly? I've got some caching issues with channels and channel permissions.

**Comment by hydrox19** [comment]
I think you should also provide your client options maybe(?)

**Comment by timotejroiko** [comment]
what is your discord.js-light version and your discord.js version?

if you have an eval command, you can do `eval require("discord.js").version`

**Comment by LosTigeros** [comment]
- discord.js-light: 4.6.0
- discord.js: 13.6.0

<details><summary>grep of `discord.js` from package-lock.json</summary>

```
$ grep 'discord.js' package-lock.json
        "discord.js-light": "^4.6.0",
    "node_modules/discord.js": {
      "resolved": "https://registry.npmjs.org/discord.js/-/discord.js-13.6.0.tgz",
    "node_modules/discord.js-light": {
      "resolved": "https://registry.npmjs.org/discord.js-light/-/discord.js-light-4.6.0.tgz",
        "discord.js": "^13.6.0"
    "discord.js": {
      "resolved": "https://registry.npmjs.org/discord.js/-/discord.js-13.6.0.tgz",
    "discord.js-light": {
      "resolved": "https://registry.npmjs.org/discord.js-light/-/discord.js-light-4.6.0.tgz",
        "discord.js": "^13.6.0"
```

</details>

**Comment by timotejroiko** [comment]
hmmm something isnt right, those errors are showing up in the wrong lines for that version

`at ChannelUpdateAction.ChannelUpdate [as handle] (./node_modules/discord.js-light/actions.js:64:4)`
in 4.6.0 this error would be at line 65 not 64

`at ThreadListSyncAction.ThreadListSync [as handle] (./node_modules/discord.js-light/actions.js:667:33)`
in 4.6.0 this error would be at line 670 not 667

try uninstalling both discord.js and discord.js-light, and installing only discord.js-light, no need to install discord.js

also, yes i do have a discord support server, its `discord.gg/BpeedKh`

**Comment by LosTigeros** [comment]
I'm sorry, it's not the 1st time `npm` messed up the packages. I just decided I'm gonna switch to `yarn`.

**Comment by LosTigeros** [comment]
Didn't have to wait long:
```
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at makePartial (./node_modules/discord.js-light/functions.js:26:9)
    at ChannelUpdateAction.ChannelUpdate [as handle] (./node_modules/discord.js-light/actions.js:65:4)
    at Object.CHANNEL_UPDATE (./node_modules/discord.js-light/handlers.js:99:57)
    at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
    at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (./node_modules/ws/lib/websocket.js:1137:20)
```

**Comment by LosTigeros** [comment]
Okay, hooked it up. Now waiting for the report.
Fun fact - this only happens on shard no. 24 :D

**Comment by LosTigeros** [comment]
Hmm this is what I've got:
```
TypeError: Cannot destructure property 'old' of 'client.actions.ChannelUpdate.handle(...)' as it is undefined.
    at Object.CHANNEL_UPDATE (./node_modules/discord.js-light/handlers.js:99:11)
    at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
    at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (./node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (./node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (./node_modules/ws/lib/receiver.js:446:17)
```

**Comment by timotejroiko** [comment]
forgot to add a return

```js
client.on("ready", () => {
    const backup = client.actions.ChannelUpdate.handle;
    client.actions.ChannelUpdate.handle = function(data) {
        try {
            return backup.call(client.actions.ChannelUpdate, data)
        } catch(e) {
            console.log(e, data);
            return {};
        }
    }
})
```

**Comment by LosTigeros** [comment]
Updated. Will get back once it reports an error.

**Comment by LosTigeros** [comment]
Okay, I've got it.

<details><summary>Data + Error stack</summary>

```json
{
  "data": {
    "available_tags": [],
    "guild_hashes": {
      "channels": {
        "hash": "4qINifI3TeQ"
      },
      "metadata": {
        "hash": "U8P+CNuVFlo"
      },
      "roles": {
        "hash": "WEAD99Co/a8"
      },
      "version": 1
    },
    "guild_id": "432763481289261077",
    "id": "951218398019342427",
    "last_message_id": "951938573207212136",
    "name": "👽question-of-the-day",
    "nsfw": false,
    "parent_id": "821529627662745681",
    "permission_overwrites": [
      {
        "allow": "0",
        "deny": "2112",
        "id": "656179690985488385",
        "type": 0
      },
      {
        "allow": "274877957120",
        "deny": "2048",
        "id": "432763481289261077",
        "type": 0
      },
      {
        "allow": "268438544",
        "deny": "0",
        "id": "467978215927840768",
        "type": 0
      },
      {
        "allow": "0",
        "deny": "268435472",
        "id": "443849268969734144",
        "type": 0
      }
    ],
    "position": 15,
    "topic": "Come here everyday, we post questions for you to answer that helps the community learn more about you and is a great way to participate in the server in the **Question of the Day!**",
    "type": 15,
    "shardId": 24
  },
  "stack": "
TypeError: Object.defineProperty called on non-object
		at Function.defineProperty (<anonymous>)
		at makePartial (./node_modules/discord.js-light/functions.js:26:9)
		at ChannelUpdateAction.ChannelUpdate (./node_modules/discord.js-light/actions.js:65:4)
		at ChannelUpdateAction.client.actions.ChannelUpdate.handle (./src/services/discord/events/ready.ts:67:22)
		at Object.CHANNEL_UPDATE (./node_modules/discord.js-light/handlers.js:100:57)
		at WebSocketManager.Client.ws.handlePacket (./node_modules/discord.js-light/client.js:47:29)
		at WebSocketShard.onPacket (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
		at WebSocketShard.onMessage (./node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
		at WebSocket.onMessage (./node_modules/ws/lib/event-target.js:199:18)
		at WebSocket.emit (node:events:390:28)
	"
}
```
</details>

**Comment by timotejroiko** [comment]
it seems like your bot has access to one of the few lucky guilds that have been selected to test drive the new `GUILD_FORUM` feature discord is working on.

I have added a patch to ignore unsupported/unreleased channel types, you can test it by running `npm install timotejroiko/discord.js-light#v4`

let me know if it resolves the issue, so i can publish it to npm

**Comment by LosTigeros** [comment]
Hey, I didn't get any issues for last 48 hours so it may be resolved. I'll get back in a 2 days with final statement.

**Comment by timotejroiko** [comment]
awesome, i pushed the update to npm, let me know if anything changes

**Comment by LosTigeros** [comment]
Hey, just wanted to confirm. I don't get that error anymore. Thanks for the fix.
